// This file was auto-generated by @joelek/autoguard. Edit at own risk.

import * as autoguard from "@joelek/autoguard/dist/lib-shared";

export const Status: autoguard.serialization.MessageGuard<Status> = autoguard.guards.Union.of(
	autoguard.guards.StringLiteral.of("OK"),
	autoguard.guards.StringLiteral.of("AUTH_ERROR"),
	autoguard.guards.StringLiteral.of("DOMAIN_OCCUPIED"),
	autoguard.guards.StringLiteral.of("RATE_LIMITED"),
	autoguard.guards.StringLiteral.of("BAD_INDATA"),
	autoguard.guards.StringLiteral.of("UNKNOWN_ERROR"),
	autoguard.guards.StringLiteral.of("INSUFFICIENT_FUNDS")
);

export type Status = autoguard.guards.Union<[
	autoguard.guards.StringLiteral<"OK">,
	autoguard.guards.StringLiteral<"AUTH_ERROR">,
	autoguard.guards.StringLiteral<"DOMAIN_OCCUPIED">,
	autoguard.guards.StringLiteral<"RATE_LIMITED">,
	autoguard.guards.StringLiteral<"BAD_INDATA">,
	autoguard.guards.StringLiteral<"UNKNOWN_ERROR">,
	autoguard.guards.StringLiteral<"INSUFFICIENT_FUNDS">
]>;

export const Domain: autoguard.serialization.MessageGuard<Domain> = autoguard.guards.Object.of({
	"domain": autoguard.guards.String,
	"paid": autoguard.guards.Boolean,
	"registered": autoguard.guards.Boolean,
	"reference_no": autoguard.guards.Integer,
	"renewal_status": autoguard.guards.Union.of(
		autoguard.guards.StringLiteral.of("NORMAL"),
		autoguard.guards.StringLiteral.of("DEACTIVATED"),
		autoguard.guards.StringLiteral.of("NOT_HANDLED_BY_LOOPIA")
	),
	"expiration_date": autoguard.guards.String
}, {});

export type Domain = autoguard.guards.Object<{
	"domain": autoguard.guards.String,
	"paid": autoguard.guards.Boolean,
	"registered": autoguard.guards.Boolean,
	"reference_no": autoguard.guards.Integer,
	"renewal_status": autoguard.guards.Union<[
		autoguard.guards.StringLiteral<"NORMAL">,
		autoguard.guards.StringLiteral<"DEACTIVATED">,
		autoguard.guards.StringLiteral<"NOT_HANDLED_BY_LOOPIA">
	]>,
	"expiration_date": autoguard.guards.String
}, {}>;

export const getDomainsRequest: autoguard.serialization.MessageGuard<getDomainsRequest> = autoguard.guards.Object.of({
	"methodName": autoguard.guards.StringLiteral.of("getDomains"),
	"parameters": autoguard.guards.Tuple.of(
		autoguard.guards.String,
		autoguard.guards.String,
		autoguard.guards.String
	)
}, {});

export type getDomainsRequest = autoguard.guards.Object<{
	"methodName": autoguard.guards.StringLiteral<"getDomains">,
	"parameters": autoguard.guards.Tuple<[
		autoguard.guards.String,
		autoguard.guards.String,
		autoguard.guards.String
	]>
}, {}>;

export const getDomainsResponse: autoguard.serialization.MessageGuard<getDomainsResponse> = autoguard.guards.Object.of({
	"parameters": autoguard.guards.Tuple.of(
		autoguard.guards.Array.of(autoguard.guards.Reference.of(() => Domain))
	)
}, {});

export type getDomainsResponse = autoguard.guards.Object<{
	"parameters": autoguard.guards.Tuple<[
		autoguard.guards.Array<autoguard.guards.Reference<Domain>>
	]>
}, {}>;

export const getSubdomainsRequest: autoguard.serialization.MessageGuard<getSubdomainsRequest> = autoguard.guards.Object.of({
	"methodName": autoguard.guards.StringLiteral.of("getSubdomains"),
	"parameters": autoguard.guards.Tuple.of(
		autoguard.guards.String,
		autoguard.guards.String,
		autoguard.guards.String,
		autoguard.guards.String
	)
}, {});

export type getSubdomainsRequest = autoguard.guards.Object<{
	"methodName": autoguard.guards.StringLiteral<"getSubdomains">,
	"parameters": autoguard.guards.Tuple<[
		autoguard.guards.String,
		autoguard.guards.String,
		autoguard.guards.String,
		autoguard.guards.String
	]>
}, {}>;

export const getSubdomainsResponse: autoguard.serialization.MessageGuard<getSubdomainsResponse> = autoguard.guards.Object.of({
	"parameters": autoguard.guards.Tuple.of(
		autoguard.guards.Array.of(autoguard.guards.String)
	)
}, {});

export type getSubdomainsResponse = autoguard.guards.Object<{
	"parameters": autoguard.guards.Tuple<[
		autoguard.guards.Array<autoguard.guards.String>
	]>
}, {}>;

export const addSubdomainRequest: autoguard.serialization.MessageGuard<addSubdomainRequest> = autoguard.guards.Object.of({
	"methodName": autoguard.guards.StringLiteral.of("addSubdomain"),
	"parameters": autoguard.guards.Tuple.of(
		autoguard.guards.String,
		autoguard.guards.String,
		autoguard.guards.String,
		autoguard.guards.String,
		autoguard.guards.String
	)
}, {});

export type addSubdomainRequest = autoguard.guards.Object<{
	"methodName": autoguard.guards.StringLiteral<"addSubdomain">,
	"parameters": autoguard.guards.Tuple<[
		autoguard.guards.String,
		autoguard.guards.String,
		autoguard.guards.String,
		autoguard.guards.String,
		autoguard.guards.String
	]>
}, {}>;

export const addSubdomainResponse: autoguard.serialization.MessageGuard<addSubdomainResponse> = autoguard.guards.Object.of({
	"parameters": autoguard.guards.Tuple.of(
		autoguard.guards.Reference.of(() => Status)
	)
}, {});

export type addSubdomainResponse = autoguard.guards.Object<{
	"parameters": autoguard.guards.Tuple<[
		autoguard.guards.Reference<Status>
	]>
}, {}>;

export const removeSubdomainRequest: autoguard.serialization.MessageGuard<removeSubdomainRequest> = autoguard.guards.Object.of({
	"methodName": autoguard.guards.StringLiteral.of("removeSubdomain"),
	"parameters": autoguard.guards.Tuple.of(
		autoguard.guards.String,
		autoguard.guards.String,
		autoguard.guards.String,
		autoguard.guards.String,
		autoguard.guards.String
	)
}, {});

export type removeSubdomainRequest = autoguard.guards.Object<{
	"methodName": autoguard.guards.StringLiteral<"removeSubdomain">,
	"parameters": autoguard.guards.Tuple<[
		autoguard.guards.String,
		autoguard.guards.String,
		autoguard.guards.String,
		autoguard.guards.String,
		autoguard.guards.String
	]>
}, {}>;

export const removeSubdomainResponse: autoguard.serialization.MessageGuard<removeSubdomainResponse> = autoguard.guards.Object.of({
	"parameters": autoguard.guards.Tuple.of(
		autoguard.guards.Reference.of(() => Status)
	)
}, {});

export type removeSubdomainResponse = autoguard.guards.Object<{
	"parameters": autoguard.guards.Tuple<[
		autoguard.guards.Reference<Status>
	]>
}, {}>;

export const Record: autoguard.serialization.MessageGuard<Record> = autoguard.guards.Object.of({
	"type": autoguard.guards.String,
	"ttl": autoguard.guards.Integer,
	"priority": autoguard.guards.Integer,
	"rdata": autoguard.guards.String,
	"record_id": autoguard.guards.Integer
}, {});

export type Record = autoguard.guards.Object<{
	"type": autoguard.guards.String,
	"ttl": autoguard.guards.Integer,
	"priority": autoguard.guards.Integer,
	"rdata": autoguard.guards.String,
	"record_id": autoguard.guards.Integer
}, {}>;

export const getZoneRecordsRequest: autoguard.serialization.MessageGuard<getZoneRecordsRequest> = autoguard.guards.Object.of({
	"methodName": autoguard.guards.StringLiteral.of("getZoneRecords"),
	"parameters": autoguard.guards.Tuple.of(
		autoguard.guards.String,
		autoguard.guards.String,
		autoguard.guards.String,
		autoguard.guards.String,
		autoguard.guards.String
	)
}, {});

export type getZoneRecordsRequest = autoguard.guards.Object<{
	"methodName": autoguard.guards.StringLiteral<"getZoneRecords">,
	"parameters": autoguard.guards.Tuple<[
		autoguard.guards.String,
		autoguard.guards.String,
		autoguard.guards.String,
		autoguard.guards.String,
		autoguard.guards.String
	]>
}, {}>;

export const getZoneRecordsResponse: autoguard.serialization.MessageGuard<getZoneRecordsResponse> = autoguard.guards.Object.of({
	"parameters": autoguard.guards.Tuple.of(
		autoguard.guards.Array.of(autoguard.guards.Reference.of(() => Record))
	)
}, {});

export type getZoneRecordsResponse = autoguard.guards.Object<{
	"parameters": autoguard.guards.Tuple<[
		autoguard.guards.Array<autoguard.guards.Reference<Record>>
	]>
}, {}>;

export const addZoneRecordRequest: autoguard.serialization.MessageGuard<addZoneRecordRequest> = autoguard.guards.Object.of({
	"methodName": autoguard.guards.StringLiteral.of("addZoneRecord"),
	"parameters": autoguard.guards.Tuple.of(
		autoguard.guards.String,
		autoguard.guards.String,
		autoguard.guards.String,
		autoguard.guards.String,
		autoguard.guards.String,
		autoguard.guards.Reference.of(() => Record)
	)
}, {});

export type addZoneRecordRequest = autoguard.guards.Object<{
	"methodName": autoguard.guards.StringLiteral<"addZoneRecord">,
	"parameters": autoguard.guards.Tuple<[
		autoguard.guards.String,
		autoguard.guards.String,
		autoguard.guards.String,
		autoguard.guards.String,
		autoguard.guards.String,
		autoguard.guards.Reference<Record>
	]>
}, {}>;

export const addZoneRecordResponse: autoguard.serialization.MessageGuard<addZoneRecordResponse> = autoguard.guards.Object.of({
	"parameters": autoguard.guards.Tuple.of(
		autoguard.guards.Reference.of(() => Status)
	)
}, {});

export type addZoneRecordResponse = autoguard.guards.Object<{
	"parameters": autoguard.guards.Tuple<[
		autoguard.guards.Reference<Status>
	]>
}, {}>;

export const updateZoneRecordRequest: autoguard.serialization.MessageGuard<updateZoneRecordRequest> = autoguard.guards.Object.of({
	"methodName": autoguard.guards.StringLiteral.of("updateZoneRecord"),
	"parameters": autoguard.guards.Tuple.of(
		autoguard.guards.String,
		autoguard.guards.String,
		autoguard.guards.String,
		autoguard.guards.String,
		autoguard.guards.String,
		autoguard.guards.Reference.of(() => Record)
	)
}, {});

export type updateZoneRecordRequest = autoguard.guards.Object<{
	"methodName": autoguard.guards.StringLiteral<"updateZoneRecord">,
	"parameters": autoguard.guards.Tuple<[
		autoguard.guards.String,
		autoguard.guards.String,
		autoguard.guards.String,
		autoguard.guards.String,
		autoguard.guards.String,
		autoguard.guards.Reference<Record>
	]>
}, {}>;

export const updateZoneRecordResponse: autoguard.serialization.MessageGuard<updateZoneRecordResponse> = autoguard.guards.Object.of({
	"parameters": autoguard.guards.Tuple.of(
		autoguard.guards.Reference.of(() => Status)
	)
}, {});

export type updateZoneRecordResponse = autoguard.guards.Object<{
	"parameters": autoguard.guards.Tuple<[
		autoguard.guards.Reference<Status>
	]>
}, {}>;

export const removeZoneRecordRequest: autoguard.serialization.MessageGuard<removeZoneRecordRequest> = autoguard.guards.Object.of({
	"methodName": autoguard.guards.StringLiteral.of("removeZoneRecord"),
	"parameters": autoguard.guards.Tuple.of(
		autoguard.guards.String,
		autoguard.guards.String,
		autoguard.guards.String,
		autoguard.guards.String,
		autoguard.guards.String,
		autoguard.guards.Integer
	)
}, {});

export type removeZoneRecordRequest = autoguard.guards.Object<{
	"methodName": autoguard.guards.StringLiteral<"removeZoneRecord">,
	"parameters": autoguard.guards.Tuple<[
		autoguard.guards.String,
		autoguard.guards.String,
		autoguard.guards.String,
		autoguard.guards.String,
		autoguard.guards.String,
		autoguard.guards.Integer
	]>
}, {}>;

export const removeZoneRecordResponse: autoguard.serialization.MessageGuard<removeZoneRecordResponse> = autoguard.guards.Object.of({
	"parameters": autoguard.guards.Tuple.of(
		autoguard.guards.Reference.of(() => Status)
	)
}, {});

export type removeZoneRecordResponse = autoguard.guards.Object<{
	"parameters": autoguard.guards.Tuple<[
		autoguard.guards.Reference<Status>
	]>
}, {}>;

export namespace Autoguard {
	export const Guards = {
		"Status": autoguard.guards.Reference.of(() => Status),
		"Domain": autoguard.guards.Reference.of(() => Domain),
		"getDomainsRequest": autoguard.guards.Reference.of(() => getDomainsRequest),
		"getDomainsResponse": autoguard.guards.Reference.of(() => getDomainsResponse),
		"getSubdomainsRequest": autoguard.guards.Reference.of(() => getSubdomainsRequest),
		"getSubdomainsResponse": autoguard.guards.Reference.of(() => getSubdomainsResponse),
		"addSubdomainRequest": autoguard.guards.Reference.of(() => addSubdomainRequest),
		"addSubdomainResponse": autoguard.guards.Reference.of(() => addSubdomainResponse),
		"removeSubdomainRequest": autoguard.guards.Reference.of(() => removeSubdomainRequest),
		"removeSubdomainResponse": autoguard.guards.Reference.of(() => removeSubdomainResponse),
		"Record": autoguard.guards.Reference.of(() => Record),
		"getZoneRecordsRequest": autoguard.guards.Reference.of(() => getZoneRecordsRequest),
		"getZoneRecordsResponse": autoguard.guards.Reference.of(() => getZoneRecordsResponse),
		"addZoneRecordRequest": autoguard.guards.Reference.of(() => addZoneRecordRequest),
		"addZoneRecordResponse": autoguard.guards.Reference.of(() => addZoneRecordResponse),
		"updateZoneRecordRequest": autoguard.guards.Reference.of(() => updateZoneRecordRequest),
		"updateZoneRecordResponse": autoguard.guards.Reference.of(() => updateZoneRecordResponse),
		"removeZoneRecordRequest": autoguard.guards.Reference.of(() => removeZoneRecordRequest),
		"removeZoneRecordResponse": autoguard.guards.Reference.of(() => removeZoneRecordResponse)
	};

	export type Guards = { [A in keyof typeof Guards]: ReturnType<typeof Guards[A]["as"]>; };

	export const Requests = {
		"sendRequest": autoguard.guards.Object.of({}, {
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Options
			),
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		})
	};

	export type Requests = { [A in keyof typeof Requests]: ReturnType<typeof Requests[A]["as"]>; };

	export const Responses = {
		"sendRequest": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		})
	};

	export type Responses = { [A in keyof typeof Responses]: ReturnType<typeof Responses[A]["as"]>; };
};
