// This file was auto-generated by @joelek/ts-autoguard. Edit at own risk.

import * as autoguard from "@joelek/ts-autoguard/dist/lib-shared";

export const DomainPrice = autoguard.guards.Object.of({
	"amount": autoguard.guards.Number,
	"currency": autoguard.guards.String,
	"years": autoguard.guards.Number
});

export type DomainPrice = ReturnType<typeof DomainPrice["as"]>;

export const RegistrarInfo = autoguard.guards.Object.of({
	"autorenew": autoguard.guards.String,
	"state": autoguard.guards.String,
	"statedescription": autoguard.guards.Union.of(
		autoguard.guards.String,
		autoguard.guards.Undefined
	),
	"expire": autoguard.guards.Union.of(
		autoguard.guards.String,
		autoguard.guards.Undefined
	),
	"tld": autoguard.guards.Union.of(
		autoguard.guards.String,
		autoguard.guards.Undefined
	),
	"invoicenumber": autoguard.guards.Union.of(
		autoguard.guards.String,
		autoguard.guards.Undefined
	)
});

export type RegistrarInfo = ReturnType<typeof RegistrarInfo["as"]>;

export const Domain = autoguard.guards.Object.of({
	"domainname": autoguard.guards.String,
	"available": autoguard.guards.Union.of(
		autoguard.guards.Boolean,
		autoguard.guards.Undefined
	),
	"createtime": autoguard.guards.Union.of(
		autoguard.guards.String,
		autoguard.guards.Undefined
	),
	"displayname": autoguard.guards.Union.of(
		autoguard.guards.String,
		autoguard.guards.Undefined
	),
	"expire": autoguard.guards.Union.of(
		autoguard.guards.Number,
		autoguard.guards.Undefined
	),
	"minimum": autoguard.guards.Union.of(
		autoguard.guards.Number,
		autoguard.guards.Undefined
	),
	"prices": autoguard.guards.Union.of(
		autoguard.guards.Array.of(autoguard.guards.Reference.of(() => DomainPrice)),
		autoguard.guards.Undefined
	),
	"primarynameserver": autoguard.guards.Union.of(
		autoguard.guards.String,
		autoguard.guards.Undefined
	),
	"recordcount": autoguard.guards.Union.of(
		autoguard.guards.Number,
		autoguard.guards.Undefined
	),
	"refresh": autoguard.guards.Union.of(
		autoguard.guards.Number,
		autoguard.guards.Undefined
	),
	"registrarinfo": autoguard.guards.Union.of(
		autoguard.guards.Reference.of(() => RegistrarInfo),
		autoguard.guards.Undefined
	),
	"responsibleperson": autoguard.guards.Union.of(
		autoguard.guards.String,
		autoguard.guards.Undefined
	),
	"retry": autoguard.guards.Union.of(
		autoguard.guards.Number,
		autoguard.guards.Undefined
	),
	"ttl": autoguard.guards.Union.of(
		autoguard.guards.Number,
		autoguard.guards.Undefined
	),
	"usingglesysnameserver": autoguard.guards.Union.of(
		autoguard.guards.String,
		autoguard.guards.Undefined
	)
});

export type Domain = ReturnType<typeof Domain["as"]>;

export const DomainRecordHost = autoguard.guards.Union.of(
	autoguard.guards.StringLiteral.of("@"),
	autoguard.guards.String
);

export type DomainRecordHost = ReturnType<typeof DomainRecordHost["as"]>;

export const DomainRecordType = autoguard.guards.Union.of(
	autoguard.guards.StringLiteral.of("A"),
	autoguard.guards.StringLiteral.of("NS"),
	autoguard.guards.StringLiteral.of("MX"),
	autoguard.guards.StringLiteral.of("TXT"),
	autoguard.guards.String
);

export type DomainRecordType = ReturnType<typeof DomainRecordType["as"]>;

export const DomainRecord = autoguard.guards.Object.of({
	"domainname": autoguard.guards.String,
	"data": autoguard.guards.String,
	"host": autoguard.guards.Reference.of(() => DomainRecordHost),
	"recordid": autoguard.guards.Number,
	"ttl": autoguard.guards.Number,
	"type": autoguard.guards.Reference.of(() => DomainRecordType)
});

export type DomainRecord = ReturnType<typeof DomainRecord["as"]>;

export namespace Autoguard {
	export const Guards = {
		"DomainPrice": autoguard.guards.Reference.of(() => DomainPrice),
		"RegistrarInfo": autoguard.guards.Reference.of(() => RegistrarInfo),
		"Domain": autoguard.guards.Reference.of(() => Domain),
		"DomainRecordHost": autoguard.guards.Reference.of(() => DomainRecordHost),
		"DomainRecordType": autoguard.guards.Reference.of(() => DomainRecordType),
		"DomainRecord": autoguard.guards.Reference.of(() => DomainRecord)
	};

	export type Guards = { [A in keyof typeof Guards]: ReturnType<typeof Guards[A]["as"]>; };

	export const Requests = {
		"listDomains": autoguard.guards.Object.of({
			"options": autoguard.guards.Union.of(
				autoguard.guards.Intersection.of(
					autoguard.guards.Object.of({}),
					autoguard.api.Options
				),
				autoguard.guards.Undefined
			),
			"headers": autoguard.guards.Union.of(
				autoguard.guards.Intersection.of(
					autoguard.guards.Object.of({}),
					autoguard.api.Headers
				),
				autoguard.guards.Undefined
			),
			"payload": autoguard.guards.Union.of(
				autoguard.api.Binary,
				autoguard.guards.Undefined
			)
		}),
		"listDomainRecords": autoguard.guards.Object.of({
			"options": autoguard.guards.Union.of(
				autoguard.guards.Intersection.of(
					autoguard.guards.Object.of({}),
					autoguard.api.Options
				),
				autoguard.guards.Undefined
			),
			"headers": autoguard.guards.Union.of(
				autoguard.guards.Intersection.of(
					autoguard.guards.Object.of({}),
					autoguard.api.Headers
				),
				autoguard.guards.Undefined
			),
			"payload": autoguard.guards.Object.of({
				"domainname": autoguard.guards.String
			})
		}),
		"createDomainRecord": autoguard.guards.Object.of({
			"options": autoguard.guards.Union.of(
				autoguard.guards.Intersection.of(
					autoguard.guards.Object.of({}),
					autoguard.api.Options
				),
				autoguard.guards.Undefined
			),
			"headers": autoguard.guards.Union.of(
				autoguard.guards.Intersection.of(
					autoguard.guards.Object.of({}),
					autoguard.api.Headers
				),
				autoguard.guards.Undefined
			),
			"payload": autoguard.guards.Object.of({
				"domainname": autoguard.guards.String,
				"data": autoguard.guards.String,
				"host": autoguard.guards.Reference.of(() => DomainRecordHost),
				"type": autoguard.guards.Reference.of(() => DomainRecordType),
				"ttl": autoguard.guards.Union.of(
					autoguard.guards.Number,
					autoguard.guards.Undefined
				)
			})
		}),
		"updateDomainRecord": autoguard.guards.Object.of({
			"options": autoguard.guards.Union.of(
				autoguard.guards.Intersection.of(
					autoguard.guards.Object.of({}),
					autoguard.api.Options
				),
				autoguard.guards.Undefined
			),
			"headers": autoguard.guards.Union.of(
				autoguard.guards.Intersection.of(
					autoguard.guards.Object.of({}),
					autoguard.api.Headers
				),
				autoguard.guards.Undefined
			),
			"payload": autoguard.guards.Object.of({
				"recordid": autoguard.guards.Number,
				"data": autoguard.guards.Union.of(
					autoguard.guards.String,
					autoguard.guards.Undefined
				),
				"host": autoguard.guards.Union.of(
					autoguard.guards.Reference.of(() => DomainRecordHost),
					autoguard.guards.Undefined
				),
				"type": autoguard.guards.Union.of(
					autoguard.guards.Reference.of(() => DomainRecordType),
					autoguard.guards.Undefined
				),
				"ttl": autoguard.guards.Union.of(
					autoguard.guards.Number,
					autoguard.guards.Undefined
				)
			})
		}),
		"deleteDomainRecord": autoguard.guards.Object.of({
			"options": autoguard.guards.Union.of(
				autoguard.guards.Intersection.of(
					autoguard.guards.Object.of({}),
					autoguard.api.Options
				),
				autoguard.guards.Undefined
			),
			"headers": autoguard.guards.Union.of(
				autoguard.guards.Intersection.of(
					autoguard.guards.Object.of({}),
					autoguard.api.Headers
				),
				autoguard.guards.Undefined
			),
			"payload": autoguard.guards.Object.of({
				"recordid": autoguard.guards.Number
			})
		})
	};

	export type Requests = { [A in keyof typeof Requests]: ReturnType<typeof Requests[A]["as"]>; };

	export const Responses = {
		"listDomains": autoguard.guards.Object.of({
			"status": autoguard.guards.Union.of(
				autoguard.guards.Number,
				autoguard.guards.Undefined
			),
			"headers": autoguard.guards.Union.of(
				autoguard.guards.Intersection.of(
					autoguard.guards.Object.of({}),
					autoguard.api.Headers
				),
				autoguard.guards.Undefined
			),
			"payload": autoguard.guards.Object.of({
				"response": autoguard.guards.Object.of({
					"domains": autoguard.guards.Array.of(autoguard.guards.Reference.of(() => Domain))
				})
			})
		}),
		"listDomainRecords": autoguard.guards.Object.of({
			"status": autoguard.guards.Union.of(
				autoguard.guards.Number,
				autoguard.guards.Undefined
			),
			"headers": autoguard.guards.Union.of(
				autoguard.guards.Intersection.of(
					autoguard.guards.Object.of({}),
					autoguard.api.Headers
				),
				autoguard.guards.Undefined
			),
			"payload": autoguard.guards.Object.of({
				"response": autoguard.guards.Object.of({
					"records": autoguard.guards.Array.of(autoguard.guards.Reference.of(() => DomainRecord))
				})
			})
		}),
		"createDomainRecord": autoguard.guards.Object.of({
			"status": autoguard.guards.Union.of(
				autoguard.guards.Number,
				autoguard.guards.Undefined
			),
			"headers": autoguard.guards.Union.of(
				autoguard.guards.Intersection.of(
					autoguard.guards.Object.of({}),
					autoguard.api.Headers
				),
				autoguard.guards.Undefined
			),
			"payload": autoguard.guards.Object.of({
				"response": autoguard.guards.Object.of({
					"record": autoguard.guards.Reference.of(() => DomainRecord)
				})
			})
		}),
		"updateDomainRecord": autoguard.guards.Object.of({
			"status": autoguard.guards.Union.of(
				autoguard.guards.Number,
				autoguard.guards.Undefined
			),
			"headers": autoguard.guards.Union.of(
				autoguard.guards.Intersection.of(
					autoguard.guards.Object.of({}),
					autoguard.api.Headers
				),
				autoguard.guards.Undefined
			),
			"payload": autoguard.guards.Object.of({
				"response": autoguard.guards.Object.of({
					"record": autoguard.guards.Reference.of(() => DomainRecord)
				})
			})
		}),
		"deleteDomainRecord": autoguard.guards.Object.of({
			"status": autoguard.guards.Union.of(
				autoguard.guards.Number,
				autoguard.guards.Undefined
			),
			"headers": autoguard.guards.Union.of(
				autoguard.guards.Intersection.of(
					autoguard.guards.Object.of({}),
					autoguard.api.Headers
				),
				autoguard.guards.Undefined
			),
			"payload": autoguard.guards.Object.of({
				"response": autoguard.guards.Object.of({})
			})
		})
	};

	export type Responses = { [A in keyof typeof Responses]: ReturnType<typeof Responses[A]["as"]>; };
};
