// This file was auto-generated by @joelek/autoguard. Edit at own risk.

import * as autoguard from "@joelek/autoguard/dist/lib-shared";

export const Config: autoguard.serialization.MessageGuard<Config> = autoguard.guards.Object.of({
	"account": autoguard.guards.String,
	"key": autoguard.guards.String
}, {});

export type Config = autoguard.guards.Object<{
	"account": autoguard.guards.String,
	"key": autoguard.guards.String
}, {}>;

export namespace Autoguard {
	export const Guards = {
		"Config": autoguard.guards.Reference.of(() => Config)
	};

	export type Guards = { [A in keyof typeof Guards]: ReturnType<typeof Guards[A]["as"]>; };

	export const Requests = {};

	export type Requests = { [A in keyof typeof Requests]: ReturnType<typeof Requests[A]["as"]>; };

	export const Responses = {};

	export type Responses = { [A in keyof typeof Responses]: ReturnType<typeof Responses[A]["as"]>; };
};
