// This file was auto-generated by @joelek/ts-autoguard. Edit at own risk.

import * as autoguard from "@joelek/ts-autoguard/dist/lib-shared";
import { Integer } from "../../asno";
import { Node } from "../../asno";
import { Null } from "../../asno";
import { ObjectIdentifier } from "../../asno";
import { OctetString } from "../../asno";
import { Sequence } from "../../asno";

export const ASNOInteger: autoguard.serialization.MessageGuard<ASNOInteger> = autoguard.guards.Reference.of(() => Integer);

export type ASNOInteger = autoguard.guards.Reference<Integer>;

export const ASNONode: autoguard.serialization.MessageGuard<ASNONode> = autoguard.guards.Reference.of(() => Node);

export type ASNONode = autoguard.guards.Reference<Node>;

export const ASNONull: autoguard.serialization.MessageGuard<ASNONull> = autoguard.guards.Reference.of(() => Null);

export type ASNONull = autoguard.guards.Reference<Null>;

export const ASNOObjectIdentifier: autoguard.serialization.MessageGuard<ASNOObjectIdentifier> = autoguard.guards.Reference.of(() => ObjectIdentifier);

export type ASNOObjectIdentifier = autoguard.guards.Reference<ObjectIdentifier>;

export const ASNOOctetString: autoguard.serialization.MessageGuard<ASNOOctetString> = autoguard.guards.Reference.of(() => OctetString);

export type ASNOOctetString = autoguard.guards.Reference<OctetString>;

export const ASNOSequence: autoguard.serialization.MessageGuard<ASNOSequence> = autoguard.guards.Reference.of(() => Sequence);

export type ASNOSequence = autoguard.guards.Reference<Sequence>;

export const AlgorithmIdentifier: autoguard.serialization.MessageGuard<AlgorithmIdentifier> = autoguard.guards.Intersection.of(
	autoguard.guards.Reference.of(() => ASNOSequence),
	autoguard.guards.Object.of({
		"data": autoguard.guards.Tuple.of(
			autoguard.guards.Reference.of(() => ASNOObjectIdentifier),
			autoguard.guards.Reference.of(() => ASNONode)
		)
	}, {})
);

export type AlgorithmIdentifier = autoguard.guards.Intersection<[
	autoguard.guards.Reference<ASNOSequence>,
	autoguard.guards.Object<{
		"data": autoguard.guards.Tuple<[
			autoguard.guards.Reference<ASNOObjectIdentifier>,
			autoguard.guards.Reference<ASNONode>
		]>
	}, {}>
]>;

export const AES256CBCAlgorithmIdentifier: autoguard.serialization.MessageGuard<AES256CBCAlgorithmIdentifier> = autoguard.guards.Intersection.of(
	autoguard.guards.Reference.of(() => AlgorithmIdentifier),
	autoguard.guards.Object.of({
		"data": autoguard.guards.Tuple.of(
			autoguard.guards.Intersection.of(
				autoguard.guards.Reference.of(() => ASNOObjectIdentifier),
				autoguard.guards.Object.of({
					"data": autoguard.guards.Union.of(
						autoguard.guards.StringLiteral.of("2.16.840.1.101.3.4.1.42"),
						autoguard.guards.StringLiteral.of("YIZIAWUDBAEq")
					)
				}, {})
			),
			autoguard.guards.Reference.of(() => ASNOOctetString)
		)
	}, {})
);

export type AES256CBCAlgorithmIdentifier = autoguard.guards.Intersection<[
	autoguard.guards.Reference<AlgorithmIdentifier>,
	autoguard.guards.Object<{
		"data": autoguard.guards.Tuple<[
			autoguard.guards.Intersection<[
				autoguard.guards.Reference<ASNOObjectIdentifier>,
				autoguard.guards.Object<{
					"data": autoguard.guards.Union<[
						autoguard.guards.StringLiteral<"2.16.840.1.101.3.4.1.42">,
						autoguard.guards.StringLiteral<"YIZIAWUDBAEq">
					]>
				}, {}>
			]>,
			autoguard.guards.Reference<ASNOOctetString>
		]>
	}, {}>
]>;

export const HMACSHA256AlgorithmIdentifier: autoguard.serialization.MessageGuard<HMACSHA256AlgorithmIdentifier> = autoguard.guards.Intersection.of(
	autoguard.guards.Reference.of(() => AlgorithmIdentifier),
	autoguard.guards.Object.of({
		"data": autoguard.guards.Tuple.of(
			autoguard.guards.Intersection.of(
				autoguard.guards.Reference.of(() => ASNOObjectIdentifier),
				autoguard.guards.Object.of({
					"data": autoguard.guards.Union.of(
						autoguard.guards.StringLiteral.of("1.2.840.113549.2.9"),
						autoguard.guards.StringLiteral.of("KoZIhvcNAgk=")
					)
				}, {})
			),
			autoguard.guards.Reference.of(() => ASNONull)
		)
	}, {})
);

export type HMACSHA256AlgorithmIdentifier = autoguard.guards.Intersection<[
	autoguard.guards.Reference<AlgorithmIdentifier>,
	autoguard.guards.Object<{
		"data": autoguard.guards.Tuple<[
			autoguard.guards.Intersection<[
				autoguard.guards.Reference<ASNOObjectIdentifier>,
				autoguard.guards.Object<{
					"data": autoguard.guards.Union<[
						autoguard.guards.StringLiteral<"1.2.840.113549.2.9">,
						autoguard.guards.StringLiteral<"KoZIhvcNAgk=">
					]>
				}, {}>
			]>,
			autoguard.guards.Reference<ASNONull>
		]>
	}, {}>
]>;

export const PBKDF2AlgorithmIdentifier1: autoguard.serialization.MessageGuard<PBKDF2AlgorithmIdentifier1> = autoguard.guards.Intersection.of(
	autoguard.guards.Reference.of(() => AlgorithmIdentifier),
	autoguard.guards.Object.of({
		"data": autoguard.guards.Tuple.of(
			autoguard.guards.Intersection.of(
				autoguard.guards.Reference.of(() => ASNOObjectIdentifier),
				autoguard.guards.Object.of({
					"data": autoguard.guards.Union.of(
						autoguard.guards.StringLiteral.of("1.2.840.113549.1.5.12"),
						autoguard.guards.StringLiteral.of("KoZIhvcNAQUM")
					)
				}, {})
			),
			autoguard.guards.Intersection.of(
				autoguard.guards.Reference.of(() => ASNOSequence),
				autoguard.guards.Object.of({
					"data": autoguard.guards.Tuple.of(
						autoguard.guards.Union.of(
							autoguard.guards.Reference.of(() => ASNOOctetString),
							autoguard.guards.Reference.of(() => AlgorithmIdentifier)
						),
						autoguard.guards.Reference.of(() => ASNOInteger),
						autoguard.guards.Reference.of(() => ASNOInteger),
						autoguard.guards.Reference.of(() => AlgorithmIdentifier)
					)
				}, {})
			)
		)
	}, {})
);

export type PBKDF2AlgorithmIdentifier1 = autoguard.guards.Intersection<[
	autoguard.guards.Reference<AlgorithmIdentifier>,
	autoguard.guards.Object<{
		"data": autoguard.guards.Tuple<[
			autoguard.guards.Intersection<[
				autoguard.guards.Reference<ASNOObjectIdentifier>,
				autoguard.guards.Object<{
					"data": autoguard.guards.Union<[
						autoguard.guards.StringLiteral<"1.2.840.113549.1.5.12">,
						autoguard.guards.StringLiteral<"KoZIhvcNAQUM">
					]>
				}, {}>
			]>,
			autoguard.guards.Intersection<[
				autoguard.guards.Reference<ASNOSequence>,
				autoguard.guards.Object<{
					"data": autoguard.guards.Tuple<[
						autoguard.guards.Union<[
							autoguard.guards.Reference<ASNOOctetString>,
							autoguard.guards.Reference<AlgorithmIdentifier>
						]>,
						autoguard.guards.Reference<ASNOInteger>,
						autoguard.guards.Reference<ASNOInteger>,
						autoguard.guards.Reference<AlgorithmIdentifier>
					]>
				}, {}>
			]>
		]>
	}, {}>
]>;

export const PBKDF2AlgorithmIdentifier2: autoguard.serialization.MessageGuard<PBKDF2AlgorithmIdentifier2> = autoguard.guards.Intersection.of(
	autoguard.guards.Reference.of(() => AlgorithmIdentifier),
	autoguard.guards.Object.of({
		"data": autoguard.guards.Tuple.of(
			autoguard.guards.Intersection.of(
				autoguard.guards.Reference.of(() => ASNOObjectIdentifier),
				autoguard.guards.Object.of({
					"data": autoguard.guards.Union.of(
						autoguard.guards.StringLiteral.of("1.2.840.113549.1.5.12"),
						autoguard.guards.StringLiteral.of("KoZIhvcNAQUM")
					)
				}, {})
			),
			autoguard.guards.Intersection.of(
				autoguard.guards.Reference.of(() => ASNOSequence),
				autoguard.guards.Object.of({
					"data": autoguard.guards.Tuple.of(
						autoguard.guards.Union.of(
							autoguard.guards.Reference.of(() => ASNOOctetString),
							autoguard.guards.Reference.of(() => AlgorithmIdentifier)
						),
						autoguard.guards.Reference.of(() => ASNOInteger),
						autoguard.guards.Reference.of(() => AlgorithmIdentifier)
					)
				}, {})
			)
		)
	}, {})
);

export type PBKDF2AlgorithmIdentifier2 = autoguard.guards.Intersection<[
	autoguard.guards.Reference<AlgorithmIdentifier>,
	autoguard.guards.Object<{
		"data": autoguard.guards.Tuple<[
			autoguard.guards.Intersection<[
				autoguard.guards.Reference<ASNOObjectIdentifier>,
				autoguard.guards.Object<{
					"data": autoguard.guards.Union<[
						autoguard.guards.StringLiteral<"1.2.840.113549.1.5.12">,
						autoguard.guards.StringLiteral<"KoZIhvcNAQUM">
					]>
				}, {}>
			]>,
			autoguard.guards.Intersection<[
				autoguard.guards.Reference<ASNOSequence>,
				autoguard.guards.Object<{
					"data": autoguard.guards.Tuple<[
						autoguard.guards.Union<[
							autoguard.guards.Reference<ASNOOctetString>,
							autoguard.guards.Reference<AlgorithmIdentifier>
						]>,
						autoguard.guards.Reference<ASNOInteger>,
						autoguard.guards.Reference<AlgorithmIdentifier>
					]>
				}, {}>
			]>
		]>
	}, {}>
]>;

export const PBES2AlgorithmIdentifier: autoguard.serialization.MessageGuard<PBES2AlgorithmIdentifier> = autoguard.guards.Intersection.of(
	autoguard.guards.Reference.of(() => AlgorithmIdentifier),
	autoguard.guards.Object.of({
		"data": autoguard.guards.Tuple.of(
			autoguard.guards.Intersection.of(
				autoguard.guards.Reference.of(() => ASNOObjectIdentifier),
				autoguard.guards.Object.of({
					"data": autoguard.guards.Union.of(
						autoguard.guards.StringLiteral.of("1.2.840.113549.1.5.13"),
						autoguard.guards.StringLiteral.of("KoZIhvcNAQUN")
					)
				}, {})
			),
			autoguard.guards.Intersection.of(
				autoguard.guards.Reference.of(() => ASNOSequence),
				autoguard.guards.Object.of({
					"data": autoguard.guards.Tuple.of(
						autoguard.guards.Reference.of(() => AlgorithmIdentifier),
						autoguard.guards.Reference.of(() => AlgorithmIdentifier)
					)
				}, {})
			)
		)
	}, {})
);

export type PBES2AlgorithmIdentifier = autoguard.guards.Intersection<[
	autoguard.guards.Reference<AlgorithmIdentifier>,
	autoguard.guards.Object<{
		"data": autoguard.guards.Tuple<[
			autoguard.guards.Intersection<[
				autoguard.guards.Reference<ASNOObjectIdentifier>,
				autoguard.guards.Object<{
					"data": autoguard.guards.Union<[
						autoguard.guards.StringLiteral<"1.2.840.113549.1.5.13">,
						autoguard.guards.StringLiteral<"KoZIhvcNAQUN">
					]>
				}, {}>
			]>,
			autoguard.guards.Intersection<[
				autoguard.guards.Reference<ASNOSequence>,
				autoguard.guards.Object<{
					"data": autoguard.guards.Tuple<[
						autoguard.guards.Reference<AlgorithmIdentifier>,
						autoguard.guards.Reference<AlgorithmIdentifier>
					]>
				}, {}>
			]>
		]>
	}, {}>
]>;

export namespace Autoguard {
	export const Guards = {
		"ASNOInteger": autoguard.guards.Reference.of(() => ASNOInteger),
		"ASNONode": autoguard.guards.Reference.of(() => ASNONode),
		"ASNONull": autoguard.guards.Reference.of(() => ASNONull),
		"ASNOObjectIdentifier": autoguard.guards.Reference.of(() => ASNOObjectIdentifier),
		"ASNOOctetString": autoguard.guards.Reference.of(() => ASNOOctetString),
		"ASNOSequence": autoguard.guards.Reference.of(() => ASNOSequence),
		"AlgorithmIdentifier": autoguard.guards.Reference.of(() => AlgorithmIdentifier),
		"AES256CBCAlgorithmIdentifier": autoguard.guards.Reference.of(() => AES256CBCAlgorithmIdentifier),
		"HMACSHA256AlgorithmIdentifier": autoguard.guards.Reference.of(() => HMACSHA256AlgorithmIdentifier),
		"PBKDF2AlgorithmIdentifier1": autoguard.guards.Reference.of(() => PBKDF2AlgorithmIdentifier1),
		"PBKDF2AlgorithmIdentifier2": autoguard.guards.Reference.of(() => PBKDF2AlgorithmIdentifier2),
		"PBES2AlgorithmIdentifier": autoguard.guards.Reference.of(() => PBES2AlgorithmIdentifier)
	};

	export type Guards = { [A in keyof typeof Guards]: ReturnType<typeof Guards[A]["as"]>; };

	export const Requests = {};

	export type Requests = { [A in keyof typeof Requests]: ReturnType<typeof Requests[A]["as"]>; };

	export const Responses = {};

	export type Responses = { [A in keyof typeof Responses]: ReturnType<typeof Responses[A]["as"]>; };
};
