// This file was auto-generated by @joelek/ts-autoguard. Edit at own risk.

import * as autoguard from "@joelek/ts-autoguard/dist/lib-shared";
import { Integer } from "../../asn1";
import { Node } from "../../asn1";
import { Null } from "../../asn1";
import { ObjectIdentifier } from "../../asn1";
import { OctetString } from "../../asn1";
import { Sequence } from "../../asn1";

export const ASN1Integer: autoguard.serialization.MessageGuard<ASN1Integer> = autoguard.guards.Reference.of(() => Integer);

export type ASN1Integer = autoguard.guards.Reference<Integer>;

export const ASN1Node: autoguard.serialization.MessageGuard<ASN1Node> = autoguard.guards.Reference.of(() => Node);

export type ASN1Node = autoguard.guards.Reference<Node>;

export const ASN1Null: autoguard.serialization.MessageGuard<ASN1Null> = autoguard.guards.Reference.of(() => Null);

export type ASN1Null = autoguard.guards.Reference<Null>;

export const ASN1ObjectIdentifier: autoguard.serialization.MessageGuard<ASN1ObjectIdentifier> = autoguard.guards.Reference.of(() => ObjectIdentifier);

export type ASN1ObjectIdentifier = autoguard.guards.Reference<ObjectIdentifier>;

export const ASN1OctetString: autoguard.serialization.MessageGuard<ASN1OctetString> = autoguard.guards.Reference.of(() => OctetString);

export type ASN1OctetString = autoguard.guards.Reference<OctetString>;

export const ASN1Sequence: autoguard.serialization.MessageGuard<ASN1Sequence> = autoguard.guards.Reference.of(() => Sequence);

export type ASN1Sequence = autoguard.guards.Reference<Sequence>;

export const AlgorithmIdentifier: autoguard.serialization.MessageGuard<AlgorithmIdentifier> = autoguard.guards.Intersection.of(
	autoguard.guards.Reference.of(() => ASN1Sequence),
	autoguard.guards.Object.of({
		"data": autoguard.guards.Tuple.of(
			autoguard.guards.Reference.of(() => ASN1ObjectIdentifier),
			autoguard.guards.Reference.of(() => ASN1Node)
		)
	}, {})
);

export type AlgorithmIdentifier = autoguard.guards.Intersection<[
	autoguard.guards.Reference<ASN1Sequence>,
	autoguard.guards.Object<{
		"data": autoguard.guards.Tuple<[
			autoguard.guards.Reference<ASN1ObjectIdentifier>,
			autoguard.guards.Reference<ASN1Node>
		]>
	}, {}>
]>;

export const AES128CBCIdentifier: autoguard.serialization.MessageGuard<AES128CBCIdentifier> = autoguard.guards.Intersection.of(
	autoguard.guards.Reference.of(() => AlgorithmIdentifier),
	autoguard.guards.Object.of({
		"data": autoguard.guards.Tuple.of(
			autoguard.guards.Intersection.of(
				autoguard.guards.Reference.of(() => ASN1ObjectIdentifier),
				autoguard.guards.Object.of({
					"data": autoguard.guards.StringLiteral.of("2.16.840.1.101.3.4.1.2")
				}, {})
			),
			autoguard.guards.Reference.of(() => ASN1OctetString)
		)
	}, {})
);

export type AES128CBCIdentifier = autoguard.guards.Intersection<[
	autoguard.guards.Reference<AlgorithmIdentifier>,
	autoguard.guards.Object<{
		"data": autoguard.guards.Tuple<[
			autoguard.guards.Intersection<[
				autoguard.guards.Reference<ASN1ObjectIdentifier>,
				autoguard.guards.Object<{
					"data": autoguard.guards.StringLiteral<"2.16.840.1.101.3.4.1.2">
				}, {}>
			]>,
			autoguard.guards.Reference<ASN1OctetString>
		]>
	}, {}>
]>;

export const AES192CBCIdentifier: autoguard.serialization.MessageGuard<AES192CBCIdentifier> = autoguard.guards.Intersection.of(
	autoguard.guards.Reference.of(() => AlgorithmIdentifier),
	autoguard.guards.Object.of({
		"data": autoguard.guards.Tuple.of(
			autoguard.guards.Intersection.of(
				autoguard.guards.Reference.of(() => ASN1ObjectIdentifier),
				autoguard.guards.Object.of({
					"data": autoguard.guards.StringLiteral.of("2.16.840.1.101.3.4.1.22")
				}, {})
			),
			autoguard.guards.Reference.of(() => ASN1OctetString)
		)
	}, {})
);

export type AES192CBCIdentifier = autoguard.guards.Intersection<[
	autoguard.guards.Reference<AlgorithmIdentifier>,
	autoguard.guards.Object<{
		"data": autoguard.guards.Tuple<[
			autoguard.guards.Intersection<[
				autoguard.guards.Reference<ASN1ObjectIdentifier>,
				autoguard.guards.Object<{
					"data": autoguard.guards.StringLiteral<"2.16.840.1.101.3.4.1.22">
				}, {}>
			]>,
			autoguard.guards.Reference<ASN1OctetString>
		]>
	}, {}>
]>;

export const AES256CBCIdentifier: autoguard.serialization.MessageGuard<AES256CBCIdentifier> = autoguard.guards.Intersection.of(
	autoguard.guards.Reference.of(() => AlgorithmIdentifier),
	autoguard.guards.Object.of({
		"data": autoguard.guards.Tuple.of(
			autoguard.guards.Intersection.of(
				autoguard.guards.Reference.of(() => ASN1ObjectIdentifier),
				autoguard.guards.Object.of({
					"data": autoguard.guards.StringLiteral.of("2.16.840.1.101.3.4.1.42")
				}, {})
			),
			autoguard.guards.Reference.of(() => ASN1OctetString)
		)
	}, {})
);

export type AES256CBCIdentifier = autoguard.guards.Intersection<[
	autoguard.guards.Reference<AlgorithmIdentifier>,
	autoguard.guards.Object<{
		"data": autoguard.guards.Tuple<[
			autoguard.guards.Intersection<[
				autoguard.guards.Reference<ASN1ObjectIdentifier>,
				autoguard.guards.Object<{
					"data": autoguard.guards.StringLiteral<"2.16.840.1.101.3.4.1.42">
				}, {}>
			]>,
			autoguard.guards.Reference<ASN1OctetString>
		]>
	}, {}>
]>;

export const HMACSHA256Identifier: autoguard.serialization.MessageGuard<HMACSHA256Identifier> = autoguard.guards.Intersection.of(
	autoguard.guards.Reference.of(() => AlgorithmIdentifier),
	autoguard.guards.Object.of({
		"data": autoguard.guards.Tuple.of(
			autoguard.guards.Intersection.of(
				autoguard.guards.Reference.of(() => ASN1ObjectIdentifier),
				autoguard.guards.Object.of({
					"data": autoguard.guards.StringLiteral.of("1.2.840.113549.2.9")
				}, {})
			),
			autoguard.guards.Reference.of(() => ASN1Null)
		)
	}, {})
);

export type HMACSHA256Identifier = autoguard.guards.Intersection<[
	autoguard.guards.Reference<AlgorithmIdentifier>,
	autoguard.guards.Object<{
		"data": autoguard.guards.Tuple<[
			autoguard.guards.Intersection<[
				autoguard.guards.Reference<ASN1ObjectIdentifier>,
				autoguard.guards.Object<{
					"data": autoguard.guards.StringLiteral<"1.2.840.113549.2.9">
				}, {}>
			]>,
			autoguard.guards.Reference<ASN1Null>
		]>
	}, {}>
]>;

export const PBKDF2Identifier1: autoguard.serialization.MessageGuard<PBKDF2Identifier1> = autoguard.guards.Intersection.of(
	autoguard.guards.Reference.of(() => AlgorithmIdentifier),
	autoguard.guards.Object.of({
		"data": autoguard.guards.Tuple.of(
			autoguard.guards.Intersection.of(
				autoguard.guards.Reference.of(() => ASN1ObjectIdentifier),
				autoguard.guards.Object.of({
					"data": autoguard.guards.StringLiteral.of("1.2.840.113549.1.5.12")
				}, {})
			),
			autoguard.guards.Intersection.of(
				autoguard.guards.Reference.of(() => ASN1Sequence),
				autoguard.guards.Object.of({
					"data": autoguard.guards.Tuple.of(
						autoguard.guards.Union.of(
							autoguard.guards.Reference.of(() => ASN1OctetString),
							autoguard.guards.Reference.of(() => AlgorithmIdentifier)
						),
						autoguard.guards.Reference.of(() => ASN1Integer),
						autoguard.guards.Reference.of(() => ASN1Integer),
						autoguard.guards.Reference.of(() => AlgorithmIdentifier)
					)
				}, {})
			)
		)
	}, {})
);

export type PBKDF2Identifier1 = autoguard.guards.Intersection<[
	autoguard.guards.Reference<AlgorithmIdentifier>,
	autoguard.guards.Object<{
		"data": autoguard.guards.Tuple<[
			autoguard.guards.Intersection<[
				autoguard.guards.Reference<ASN1ObjectIdentifier>,
				autoguard.guards.Object<{
					"data": autoguard.guards.StringLiteral<"1.2.840.113549.1.5.12">
				}, {}>
			]>,
			autoguard.guards.Intersection<[
				autoguard.guards.Reference<ASN1Sequence>,
				autoguard.guards.Object<{
					"data": autoguard.guards.Tuple<[
						autoguard.guards.Union<[
							autoguard.guards.Reference<ASN1OctetString>,
							autoguard.guards.Reference<AlgorithmIdentifier>
						]>,
						autoguard.guards.Reference<ASN1Integer>,
						autoguard.guards.Reference<ASN1Integer>,
						autoguard.guards.Reference<AlgorithmIdentifier>
					]>
				}, {}>
			]>
		]>
	}, {}>
]>;

export const PBKDF2Identifier2: autoguard.serialization.MessageGuard<PBKDF2Identifier2> = autoguard.guards.Intersection.of(
	autoguard.guards.Reference.of(() => AlgorithmIdentifier),
	autoguard.guards.Object.of({
		"data": autoguard.guards.Tuple.of(
			autoguard.guards.Intersection.of(
				autoguard.guards.Reference.of(() => ASN1ObjectIdentifier),
				autoguard.guards.Object.of({
					"data": autoguard.guards.StringLiteral.of("1.2.840.113549.1.5.12")
				}, {})
			),
			autoguard.guards.Intersection.of(
				autoguard.guards.Reference.of(() => ASN1Sequence),
				autoguard.guards.Object.of({
					"data": autoguard.guards.Tuple.of(
						autoguard.guards.Union.of(
							autoguard.guards.Reference.of(() => ASN1OctetString),
							autoguard.guards.Reference.of(() => AlgorithmIdentifier)
						),
						autoguard.guards.Reference.of(() => ASN1Integer),
						autoguard.guards.Reference.of(() => AlgorithmIdentifier)
					)
				}, {})
			)
		)
	}, {})
);

export type PBKDF2Identifier2 = autoguard.guards.Intersection<[
	autoguard.guards.Reference<AlgorithmIdentifier>,
	autoguard.guards.Object<{
		"data": autoguard.guards.Tuple<[
			autoguard.guards.Intersection<[
				autoguard.guards.Reference<ASN1ObjectIdentifier>,
				autoguard.guards.Object<{
					"data": autoguard.guards.StringLiteral<"1.2.840.113549.1.5.12">
				}, {}>
			]>,
			autoguard.guards.Intersection<[
				autoguard.guards.Reference<ASN1Sequence>,
				autoguard.guards.Object<{
					"data": autoguard.guards.Tuple<[
						autoguard.guards.Union<[
							autoguard.guards.Reference<ASN1OctetString>,
							autoguard.guards.Reference<AlgorithmIdentifier>
						]>,
						autoguard.guards.Reference<ASN1Integer>,
						autoguard.guards.Reference<AlgorithmIdentifier>
					]>
				}, {}>
			]>
		]>
	}, {}>
]>;

export const PBKDF2Identifier: autoguard.serialization.MessageGuard<PBKDF2Identifier> = autoguard.guards.Union.of(
	autoguard.guards.Reference.of(() => PBKDF2Identifier1),
	autoguard.guards.Reference.of(() => PBKDF2Identifier2)
);

export type PBKDF2Identifier = autoguard.guards.Union<[
	autoguard.guards.Reference<PBKDF2Identifier1>,
	autoguard.guards.Reference<PBKDF2Identifier2>
]>;

export const PBES2Identifier: autoguard.serialization.MessageGuard<PBES2Identifier> = autoguard.guards.Intersection.of(
	autoguard.guards.Reference.of(() => AlgorithmIdentifier),
	autoguard.guards.Object.of({
		"data": autoguard.guards.Tuple.of(
			autoguard.guards.Intersection.of(
				autoguard.guards.Reference.of(() => ASN1ObjectIdentifier),
				autoguard.guards.Object.of({
					"data": autoguard.guards.StringLiteral.of("1.2.840.113549.1.5.13")
				}, {})
			),
			autoguard.guards.Intersection.of(
				autoguard.guards.Reference.of(() => ASN1Sequence),
				autoguard.guards.Object.of({
					"data": autoguard.guards.Tuple.of(
						autoguard.guards.Reference.of(() => AlgorithmIdentifier),
						autoguard.guards.Reference.of(() => AlgorithmIdentifier)
					)
				}, {})
			)
		)
	}, {})
);

export type PBES2Identifier = autoguard.guards.Intersection<[
	autoguard.guards.Reference<AlgorithmIdentifier>,
	autoguard.guards.Object<{
		"data": autoguard.guards.Tuple<[
			autoguard.guards.Intersection<[
				autoguard.guards.Reference<ASN1ObjectIdentifier>,
				autoguard.guards.Object<{
					"data": autoguard.guards.StringLiteral<"1.2.840.113549.1.5.13">
				}, {}>
			]>,
			autoguard.guards.Intersection<[
				autoguard.guards.Reference<ASN1Sequence>,
				autoguard.guards.Object<{
					"data": autoguard.guards.Tuple<[
						autoguard.guards.Reference<AlgorithmIdentifier>,
						autoguard.guards.Reference<AlgorithmIdentifier>
					]>
				}, {}>
			]>
		]>
	}, {}>
]>;

export const EncryptedPrivateKeyInfo: autoguard.serialization.MessageGuard<EncryptedPrivateKeyInfo> = autoguard.guards.Intersection.of(
	autoguard.guards.Reference.of(() => ASN1Sequence),
	autoguard.guards.Object.of({
		"data": autoguard.guards.Tuple.of(
			autoguard.guards.Reference.of(() => AlgorithmIdentifier),
			autoguard.guards.Reference.of(() => ASN1OctetString)
		)
	}, {})
);

export type EncryptedPrivateKeyInfo = autoguard.guards.Intersection<[
	autoguard.guards.Reference<ASN1Sequence>,
	autoguard.guards.Object<{
		"data": autoguard.guards.Tuple<[
			autoguard.guards.Reference<AlgorithmIdentifier>,
			autoguard.guards.Reference<ASN1OctetString>
		]>
	}, {}>
]>;

export namespace Autoguard {
	export const Guards = {
		"ASN1Integer": autoguard.guards.Reference.of(() => ASN1Integer),
		"ASN1Node": autoguard.guards.Reference.of(() => ASN1Node),
		"ASN1Null": autoguard.guards.Reference.of(() => ASN1Null),
		"ASN1ObjectIdentifier": autoguard.guards.Reference.of(() => ASN1ObjectIdentifier),
		"ASN1OctetString": autoguard.guards.Reference.of(() => ASN1OctetString),
		"ASN1Sequence": autoguard.guards.Reference.of(() => ASN1Sequence),
		"AlgorithmIdentifier": autoguard.guards.Reference.of(() => AlgorithmIdentifier),
		"AES128CBCIdentifier": autoguard.guards.Reference.of(() => AES128CBCIdentifier),
		"AES192CBCIdentifier": autoguard.guards.Reference.of(() => AES192CBCIdentifier),
		"AES256CBCIdentifier": autoguard.guards.Reference.of(() => AES256CBCIdentifier),
		"HMACSHA256Identifier": autoguard.guards.Reference.of(() => HMACSHA256Identifier),
		"PBKDF2Identifier1": autoguard.guards.Reference.of(() => PBKDF2Identifier1),
		"PBKDF2Identifier2": autoguard.guards.Reference.of(() => PBKDF2Identifier2),
		"PBKDF2Identifier": autoguard.guards.Reference.of(() => PBKDF2Identifier),
		"PBES2Identifier": autoguard.guards.Reference.of(() => PBES2Identifier),
		"EncryptedPrivateKeyInfo": autoguard.guards.Reference.of(() => EncryptedPrivateKeyInfo)
	};

	export type Guards = { [A in keyof typeof Guards]: ReturnType<typeof Guards[A]["as"]>; };

	export const Requests = {};

	export type Requests = { [A in keyof typeof Requests]: ReturnType<typeof Requests[A]["as"]>; };

	export const Responses = {};

	export type Responses = { [A in keyof typeof Responses]: ReturnType<typeof Responses[A]["as"]>; };
};
