// This file was auto-generated by @joelek/ts-autoguard. Edit at own risk.

import * as autoguard from "@joelek/ts-autoguard/dist/lib-shared";

export const Config = autoguard.guards.Object.of({
	"agree_to_tos": autoguard.guards.Boolean,
	"contact": autoguard.guards.Array.of(autoguard.guards.String),
	"directories": autoguard.guards.Object.of({
		"staging": autoguard.guards.String,
		"production": autoguard.guards.String
	}),
	"domains": autoguard.guards.Array.of(autoguard.guards.Object.of({
		"hostname": autoguard.guards.String,
		"wildcard": autoguard.guards.Boolean
	}))
});

export type Config = ReturnType<typeof Config["as"]>;

export namespace Autoguard {
	export const Guards = {
		"Config": autoguard.guards.Reference.of(() => Config)
	};

	export type Guards = { [A in keyof typeof Guards]: ReturnType<typeof Guards[A]["as"]>; };

	export const Requests = {};

	export type Requests = { [A in keyof typeof Requests]: ReturnType<typeof Requests[A]["as"]>; };

	export const Responses = {};

	export type Responses = { [A in keyof typeof Responses]: ReturnType<typeof Responses[A]["as"]>; };
};
