// This file was auto-generated by @joelek/ts-autoguard. Edit at own risk.

import * as autoguard from "@joelek/ts-autoguard/dist/lib-shared";
import { AlgorithmIdentifier } from "../../pkcs5";
import { BitString } from "../../asno";
import { Integer } from "../../asno";
import { OctetString } from "../../asno";
import { Sequence } from "../../asno";

export const ASNOBitString: autoguard.serialization.MessageGuard<ASNOBitString> = autoguard.guards.Reference.of(() => BitString);

export type ASNOBitString = autoguard.guards.Reference<BitString>;

export const ASNOInteger: autoguard.serialization.MessageGuard<ASNOInteger> = autoguard.guards.Reference.of(() => Integer);

export type ASNOInteger = autoguard.guards.Reference<Integer>;

export const ASNOOctetString: autoguard.serialization.MessageGuard<ASNOOctetString> = autoguard.guards.Reference.of(() => OctetString);

export type ASNOOctetString = autoguard.guards.Reference<OctetString>;

export const ASNOSequence: autoguard.serialization.MessageGuard<ASNOSequence> = autoguard.guards.Reference.of(() => Sequence);

export type ASNOSequence = autoguard.guards.Reference<Sequence>;

export const PKCS5AlgorithmIdentifier: autoguard.serialization.MessageGuard<PKCS5AlgorithmIdentifier> = autoguard.guards.Reference.of(() => AlgorithmIdentifier);

export type PKCS5AlgorithmIdentifier = autoguard.guards.Reference<AlgorithmIdentifier>;

export const PublicKeyInfo: autoguard.serialization.MessageGuard<PublicKeyInfo> = autoguard.guards.Intersection.of(
	autoguard.guards.Reference.of(() => ASNOSequence),
	autoguard.guards.Object.of({
		"data": autoguard.guards.Tuple.of(
			autoguard.guards.Reference.of(() => PKCS5AlgorithmIdentifier),
			autoguard.guards.Reference.of(() => ASNOBitString)
		)
	}, {})
);

export type PublicKeyInfo = autoguard.guards.Intersection<[
	autoguard.guards.Reference<ASNOSequence>,
	autoguard.guards.Object<{
		"data": autoguard.guards.Tuple<[
			autoguard.guards.Reference<PKCS5AlgorithmIdentifier>,
			autoguard.guards.Reference<ASNOBitString>
		]>
	}, {}>
]>;

export const PrivateKeyInfo: autoguard.serialization.MessageGuard<PrivateKeyInfo> = autoguard.guards.Intersection.of(
	autoguard.guards.Reference.of(() => ASNOSequence),
	autoguard.guards.Object.of({
		"data": autoguard.guards.Tuple.of(
			autoguard.guards.Reference.of(() => ASNOInteger),
			autoguard.guards.Reference.of(() => PKCS5AlgorithmIdentifier),
			autoguard.guards.Reference.of(() => ASNOOctetString)
		)
	}, {})
);

export type PrivateKeyInfo = autoguard.guards.Intersection<[
	autoguard.guards.Reference<ASNOSequence>,
	autoguard.guards.Object<{
		"data": autoguard.guards.Tuple<[
			autoguard.guards.Reference<ASNOInteger>,
			autoguard.guards.Reference<PKCS5AlgorithmIdentifier>,
			autoguard.guards.Reference<ASNOOctetString>
		]>
	}, {}>
]>;

export const EncryptedPrivateKeyInfo: autoguard.serialization.MessageGuard<EncryptedPrivateKeyInfo> = autoguard.guards.Intersection.of(
	autoguard.guards.Reference.of(() => ASNOSequence),
	autoguard.guards.Object.of({
		"data": autoguard.guards.Tuple.of(
			autoguard.guards.Reference.of(() => PKCS5AlgorithmIdentifier),
			autoguard.guards.Reference.of(() => ASNOOctetString)
		)
	}, {})
);

export type EncryptedPrivateKeyInfo = autoguard.guards.Intersection<[
	autoguard.guards.Reference<ASNOSequence>,
	autoguard.guards.Object<{
		"data": autoguard.guards.Tuple<[
			autoguard.guards.Reference<PKCS5AlgorithmIdentifier>,
			autoguard.guards.Reference<ASNOOctetString>
		]>
	}, {}>
]>;

export namespace Autoguard {
	export const Guards = {
		"ASNOBitString": autoguard.guards.Reference.of(() => ASNOBitString),
		"ASNOInteger": autoguard.guards.Reference.of(() => ASNOInteger),
		"ASNOOctetString": autoguard.guards.Reference.of(() => ASNOOctetString),
		"ASNOSequence": autoguard.guards.Reference.of(() => ASNOSequence),
		"PKCS5AlgorithmIdentifier": autoguard.guards.Reference.of(() => PKCS5AlgorithmIdentifier),
		"PublicKeyInfo": autoguard.guards.Reference.of(() => PublicKeyInfo),
		"PrivateKeyInfo": autoguard.guards.Reference.of(() => PrivateKeyInfo),
		"EncryptedPrivateKeyInfo": autoguard.guards.Reference.of(() => EncryptedPrivateKeyInfo)
	};

	export type Guards = { [A in keyof typeof Guards]: ReturnType<typeof Guards[A]["as"]>; };

	export const Requests = {};

	export type Requests = { [A in keyof typeof Requests]: ReturnType<typeof Requests[A]["as"]>; };

	export const Responses = {};

	export type Responses = { [A in keyof typeof Responses]: ReturnType<typeof Responses[A]["as"]>; };
};
